---
title: "Starter Notebook"
author: "You, Scientist"
format: html
execute:
  keep-md: true
---
```{r}
#Load in any packages you need
library(tidyverse)

#Read in any data

```

```{r}
instructors <- c("Duryea", "Gilbert")

instructors
```
Challenge 1: List of nucleotides

```{r}
nucleotides <- c("Adenosine", "Guanine","Cytosine","Thymine")
nucleotides
```
Challenge 2: Random string of 15 nucleotides

```{r}
numNucleotide <- 15

randGenome <- sample(nucleotides, size = numNucleotide, replace = TRUE)

randGenome
```
```{r}
numNucleotide <- 1500

randGenome <- sample(nucleotides, size = numNucleotide, replace = TRUE)

randGenome <- paste(randGenome, collapse ="")

randGenome

```
Challenge 4: Generate a random genome of 100 nucleotides and count adenosine

```{r}
set.seed(215)
numNucleotide <- 100

randGenome <- sample(nucleotides, size = numNucleotide, replace = TRUE)

randGenome <- paste(randGenome, collapse ="")

randGenome
```

```{r}
myProduct <- 1

for(j in 1:15){
  myProduct <- myProduct + j
  print(myProduct)
}

```


